# This file was automatically generated by SWIG
package swig;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package swig;
bootstrap swig;
var__init();
package swig;
@EXPORT = qw( );
1;
