# This file was automatically generated by SWIG
package text;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package text;
bootstrap text;
var_text_init();
package text;
@EXPORT = qw( );
1;
