#!/usr/bin/env python

# Remove CVS header lines from source files

import os

cvstags = ["$RCSfile:", "$Revision:", "$Author:", "$Date:"]
excludedirs = [".git"]

def badline(line):
    for tag in cvstags:
        if tag in line:
            return True
    return False;

for root, dirs, files in os.walk("."):
    if root not in excludedirs and not root.startswith("builddir"):
        for filename in files:
            if filename.endswith(('.py', '.C', '.h', 'swg', '.spy')):
                fullname = os.path.join(root, filename)
                savename = fullname + ".back"
                os.rename(fullname, savename)
                infile = open(savename, 'r')
                outfile = open(fullname, 'w')
                print "Rewriting", fullname
                for line in infile:
                    if not badline(line):
                        print >> outfile, line,
                outfile.close()
                infile.close()
                os.remove(savename)
                    
            
