#!/usr/bin/env python
import sys, string, os, subprocess

build_types_2D = ('dist', 'devel', 'debug', 'profile')
build_types_3D = ('dist3d', 'debug3d', 'profile3d')
build_types = build_types_2D + build_types_3D

if len(sys.argv) < 2:
    print "No build version specified"
    sys.exit()
if sys.argv[1] not in build_types:
    print "Unrecognized build version", sys.argv[1]

build_type = sys.argv[1]
if build_type in build_types_2D:
    buildname = 'oof2'
else:
    buildname = 'oof3d'

pyversion = string.join(map(str, sys.version_info[:2]),".")

proc = subprocess.Popen(['git', 'symbolic-ref', '--short', 'HEAD'],
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
stdoutdata, stderrdata = proc.communicate()
if stderrdata:
    print "*** Failed to get git branch name!", stderrdata.strip()
    branchtag = ""
else:
    branchtag = stdoutdata.strip()

localdir = os.path.split(os.getcwd())[1]
if localdir.startswith('OOF3D'):
    localdir = localdir[5:]

installdir = os.getenv("OOFINSTALL")
if not installdir:
    installdir = os.getenv("HOME")

stowdir = os.path.join(installdir, 'stow')
builddir =  "-".join(["builddir", branchtag, build_type])
if localdir:
    stowsubdir = "-".join([buildname, branchtag, localdir, build_type,
                           pyversion])
else:
    stowsubdir = "-".join([buildname, branchtag, build_type, pyversion])
if build_type in ('dist3d', 'debug3d', 'profile3d'):
    laststowfile = os.path.join(stowdir, '.last_oof3d_install')
else:
    laststowfile = os.path.join(stowdir, '.last_oof_install')
startdir = os.getcwd()

try:
    lsf = file(laststowfile, "r")
    laststow = lsf.readline().rstrip()
    lsf.close()
except IOError:
    laststow = None


# Clean out the stow directory
os.chdir(stowdir)
try:
    if laststow == stowsubdir:
        print "Unstowing", stowsubdir, "from", stowdir
        os.system('stow -D %s' % stowsubdir)
        os.remove(laststowfile)
    print "Emptying", os.path.join(stowdir, stowsubdir)
    os.system('rm -rf %s' % stowsubdir) # os.removedirs is clunky.
finally:
    os.chdir(startdir)

os.rename(builddir, 'build')
if build_type in ('dist3d', 'debug3d', 'profile3d'):
	  os.system('python setup.py clean --most --swig --3D')
else:
	  os.system('python setup.py clean --most --swig')
if os.path.exists('build'):
    os.rename('build', builddir)
else:
    os.mkdir(builddir)
    if sys.platform == 'darwin':
        subprocess.check_call(['tmutil', 'addexclusion',
                               os.path.abspath(builddir)])
