#!/bin/csh
set PDIR=$1
setenv PYTHONPATH $PDIR
python $PDIR/teststiffness.py -n 1 -3 -o 1 | $PDIR/mtx_compare -t 1.e-5 - K_1x1_tri3
python $PDIR/teststiffness.py -n 3 -3 -o 1 | $PDIR/mtx_compare -t 1.e-5 - K_3x3_tri3
python $PDIR/teststiffness.py -n 1 -4 -o 1 | $PDIR/mtx_compare -t 1.e-5 - K_1x1_quad4
python $PDIR/teststiffness.py -n 3 -4 -o 1 | $PDIR/mtx_compare -t 1.e-5 - K_3x3_quad4
python $PDIR/teststiffness.py -n 1 -3 -o 2 | $PDIR/mtx_compare -t 1.e-5 - K_1x1_tri6
python $PDIR/teststiffness.py -n 1 -4 -o 2 | $PDIR/mtx_compare -t 1.e-5 - K_1x1_quad8
python $PDIR/teststiffness.py -n 3 -3 -o 2 | $PDIR/mtx_compare -t 1.e-5 - K_3x3_tri6
python $PDIR/teststiffness.py -n 3 -4 -o 2 | $PDIR/mtx_compare -t 1.e-5 - K_3x3_quad8
