multinherit.i : Line 43. private inheritance not supported (ignored).
multinherit.i : Line 50. protected inheritance not supported (ignored).
multinherit.i : Line 57. No access specifier given for base class a (ignored).
multinherit.i : Line 62. No access specifier given for base class a (ignored).
multinherit.i : Line 72. private inheritance not supported (ignored).
multinherit.i : Line 73. private inheritance not supported (ignored).
multinherit.i : Line 74. private inheritance not supported (ignored).
multinherit.i : Line 75. protected inheritance not supported (ignored).
multinherit.i : Line 76. protected inheritance not supported (ignored).
multinherit.i : Line 77. protected inheritance not supported (ignored).
multinherit.i : Line 78. No access specifier given for base class j (ignored).
multinherit.i : Line 79. No access specifier given for base class k (ignored).
