# This makefile tests the SWIG parser itself to make sure it
# doesn't croak.

all::
	@sh make.sh

endif::
	../../swig missing_endif.i
	@echo "done"

clean::
	rm -f *_wrap* *.pm *.py *.o *.output *~




