OOF.Microstructure.New(name='microstructure', width=1.0, height=1.0, depth=1.0, width_in_pixels=10, height_in_pixels=10, depth_in_pixels=10)
OOF.Skeleton.New(name='skeleton', microstructure='microstructure', x_elements=4, y_elements=4, z_elements=4, skeleton_geometry=TetraSkeleton(arrangement='moderate'))
OOF.Windows.Graphics.New()
OOF.FaceSelection.Select_Named_Boundary(skeleton='microstructure:skeleton', boundary='front')
OOF.SegmentSelection.Select_from_Selected_Faces(skeleton='microstructure:skeleton', internal=False, boundary=True)
OOF.FaceSelection.Clear(skeleton='microstructure:skeleton')
OOF.NodeSelection.Select_from_Selected_Segments(skeleton='microstructure:skeleton')
OOF.SegmentSelection.Clear(skeleton='microstructure:skeleton')
OOF.Skeleton.Boundary.Construct(skeleton='microstructure:skeleton', name='boundary', constructor=EdgeFromNodes(group=selection,direction='Clockwise-z'))
